In [2]:
import pandas as pd
import numpy as np

In [3]:
# Import the data
df = pd.read_csv('country_names.csv')
df.head()

    Country Name Country Like
0    Johnny Cash  4,997 votes
1  Hank Williams  3,721 votes
2  George Strait  4,732 votes
3  Merle Haggard  3,498 votes
4   Alan Jackson  3,606 votes

In [ ]:
1920 2
1930 3
1940 4
1950 5
1960 6
1970 7
1980 8
1990 9
2000 00
2010 10
2020 20

In [9]:
era = [6,5,8,7,9,7,6,7,6,8,7,6,8,9,8,6,8,9,7,00,7,10,7,8,9,00,00,9,7,10,9,7,6,6,7,6,8,7,9,6,20,7,8,10,7,8,00,9,20,8,00,10,9,7,7,6,7,8,10,7,4,7,3,4,5,9,6,10,9,5,00,7,10,5,7,00,6,00,9,9,9,5,9,8,3,6,10,6,7,10,00,10,6,9,5,8,9,8,5,10]
print(len(era))

100

In [7]:
era_fix = []
era = [6,5,8,7,9,7,6,7,6,8,7,6,8,9,8,6,8,9,7,00,7,10,7,8,9,00,00,9,7,10,9,7,6,6,7,6,8,7,9,6,20,7,8,10,7,8,00,9,20,8,00,10,9,7,7,6,7,8,10,7,4,7,3,4,5,9,6,10,9,5,00,7,10,5,7,00,6,00,9,9,9,5,9,8,3,6,10,6,7,10,00,10,6,9,5,8,9,8,5,10]
for x in range(len(era)):
    if era[x] == 2:
        era_fix.append('1920s')
    if era[x] == 3:
        era_fix.append('1930s')
    elif era[x] == 4:
        era_fix.append('1940s')
    elif era[x] == 5:
        era_fix.append('1950s')
    elif era[x] == 6:
        era_fix.append('1960s')
    elif era[x] == 7:
        era_fix.append('1970s')
    elif era[x] == 8:
        era_fix.append('1980s')
    elif era[x] == 9:
        era_fix.append('1990s')
    elif era[x] == 00:
        era_fix.append('2000s')
    elif era[x] == 10:
        era_fix.append('2010s')
    elif era[x] == 20:
        era_fix.append('2020s')

['1960s',
 '1950s',
 '1980s',
 '1970s',
 '1990s',
 '1970s',
 '1960s',
 '1970s',
 '1960s',
 '1980s',
 '1970s',
 '1960s',
 '1980s',
 '1990s',
 '1980s',
 '1960s',
 '1980s',
 '1990s',
 '1970s',
 '2000s',
 '1970s',
 '2010s',
 '1970s',
 '1980s',
 '1990s',
 '2000s',
 '2000s',
 '1990s',
 '1970s',
 '2010s',
 '1990s',
 '1970s',
 '1960s',
 '1960s',
 '1970s',
 '1960s',
 '1980s',
 '1970s',
 '1990s',
 '1960s',
 '2020s',
 '1970s',
 '1980s',
 '2010s',
 '1970s',
 '1980s',
 '2000s',
 '1990s',
 '2020s',
 '1980s',
 '2000s',
 '2010s',
 '1990s',
 '1970s',
 '1970s',
 '1960s',
 '1970s',
 '1980s',
 '2010s',
 '1970s',
 '1940s',
 '1970s',
 '1930s',
 '1940s',
 '1950s',
 '1990s',
 '1960s',
 '2010s',
 '1990s',
 '1950s',
 '2000s',
 '1970s',
 '2010s',
 '1950s',
 '1970s',
 '2000s',
 '1960s',
 '2000s',
 '1990s',
 '1990s',
 '1990s',
 '1950s',
 '1990s',
 '1980s',
 '1930s',
 '1960s',
 '2010s',
 '1960s',
 '1970s',
 '2010s',
 '2000s',
 '2010s',
 '1960s',
 '1990s',
 '1950s',
 '1980s',
 '1990s',
 '1980s',
 '1950s',
 '2010s']

In [29]:
era = [6,5,8,7,9,7,6,7,6,8,7,6,8,9,8,6,8,9,7,00,7,10,7,8,9,00,00,9,7,10,9,7,6,6,7,6,8,7,9,6,20,7,8,10,7,8,00,9,20,8,00,10,9,7,7,6,7,8,10,7,4,7,3,4,5,9,6,10,9,5,00,7,10,5,7,00,6,00,9,9,9,5,9,8,3,6,10,6,7,10,00,10,6,9,5,8,9,8,5,10]
era.count(20)

2

In [11]:
country = pd.read_csv('country_names.csv')
country["Era"] = era_fix

In [14]:
country = country.drop('Country Like' , axis=1)
country.to_csv('country_names.csv',index=False)
country.head()

    Country Name    Era
0    Johnny Cash  1960s
1  Hank Williams  1950s
2  George Strait  1980s
3  Merle Haggard  1970s
4   Alan Jackson  1990s

In [4]:
[6,5,8,7,9,7,6,7,6,8,7,6,8,9,8,6,8,9,7,00,7,10,7,8,9,00,00,9,7,10,9,7,6,6,7,6,8,7,9,6,20,7,8,10,7,8,00,9,20,8,00,10,9,7,7,6,7,8,10,7,4,7,3,4,5,9,6,10,9,5,00,7,10,5,7,00,6,00,9,9,9,5,9,8,3,6,10,6,7,10,00,10,6,9,5,8,9,8,5,10]
df.tail(60)

                           Country Name Country Like
63                           Gene Autry    364 votes
64                           Jim Reeves    364 votes
65                       Tracy Lawrence    957 votes
66                     June Carter Cash    891 votes
67                      Miranda Lambert    959 votes
68                         Wynonna Judd  1,188 votes
69                            Ray Price    244 votes
70                           Faith Hill    828 votes
71                           The Eagles  1,053 votes
72                       Dierks Bentley  1,194 votes
73                        Johnny Horton    789 votes
74                           Mel Tillis    848 votes
75                    Montgomery Gentry    716 votes
76                 The Statler Brothers    689 votes
77                          LeAnn Rimes  1,065 votes
78                           Pam Tillis    475 votes
79                         Marty Stuart    256 votes
80                          Diamond Rio    530 votes
81                      Jerry Lee Lewis    675 votes
82                        Sammy Kershaw    718 votes
83                         Chris LeDoux    493 votes
84                            Bob Wills    694 votes
85                       Lefty Frizzell    629 votes
86                         Jason Aldean    884 votes
87                          Tom T. Hall    542 votes
88                        Eddie Rabbitt    618 votes
89                        Darius Rucker    915 votes
90                      Trisha Yearwood  1,059 votes
91                          Keith Urban    747 votes
92                            Roy Clark    982 votes
93                        Mark Chesnutt    709 votes
94                          Ray Charles    650 votes
95                          Kitty Wells    417 votes
96                           Bobby Bare    558 votes
97                       Patty Loveless    832 votes
98                        Rascal Flatts  1,161 votes
99                         Ricky Skaggs    998 votes
100                       Lorrie Morgan    298 votes
101                            Lonestar    669 votes
102                The Bellamy Brothers    674 votes
103         Lester Flatt & Earl Scruggs    475 votes
104                          Gary Allan    673 votes
105                              Lady A    546 votes
106                         Chet Atkins  1,011 votes
107                           Hank Snow    727 votes
108                   Ricky Van Shelton    363 votes
109                        Charlie Rich    861 votes
110                      Lee Ann Womack    641 votes
111                          Roy Rogers    467 votes
112  Bill Monroe and His Bluegrass Boys    734 votes
113                           Roy Acuff    864 votes
114                         Steve Earle    485 votes
115                         Eddy Arnold    779 votes
116                     Kacey Musgraves    395 votes
117            The Marshall Tucker Band    504 votes
118                      Porter Wagoner    242 votes
119                    Billy Currington    695 votes
120                    Barbara Mandrell    482 votes
121                         Clay Walker    371 votes
122                           Jon Pardi    609 votes