In [2]:
import pandas as pd
import numpy as np
import spacy

In [3]:
csv_rap_final = pd.read_csv('/home/lettuce/MyCode/pandasproject/Rap-vs-Country-StatisticalStudy/final_rap.csv')
csv_rap_final.head()

,Artist Name,the,you,a,i,to,and,in,it,up,...,place,work,nobody,park,kneel,totin,should,arm,pay,homage
0,Total,491.0,372.0,325.0,306.0,271.0,241.0,162.0,152.0,147.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
1,The Notorious B.I.G.,85.0,82.0,90.0,73.0,70.0,51.0,37.0,30.0,10.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,Tupac,100.0,75.0,38.0,38.0,45.0,37.0,18.0,47.0,22.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,Eminem,85.0,82.0,90.0,73.0,70.0,51.0,37.0,30.0,10.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,Kendrick Lamar,74.0,36.0,36.0,40.0,14.0,29.0,23.0,17.0,75.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df = pd.read_csv('/home/lettuce/MyCode/pandasproject/rap_end.csv')

# Load the English model in Spacy
nlp = spacy.load('en_core_web_sm')

# Define a function to check if a word is a noun, verb, or adjective
def is_noun_verb_adj(word):
    pos = nlp(word)[0].pos_
    return pos in ['NOUN', 'VERB', 'ADJ']

# Iterate over columns and drop those not meeting the criteria
for col in df.columns:
    if not is_noun_verb_adj(col):
        df = df.drop(columns=[col])
        
df.head()

,Artist Name,got,get,dont,way,know,see,do,cause,aint,...,free,pour,fame,flock,times,normal,wanted,godzilla,breath,liveget
0,Total,93.0,87.0,82.0,73.0,69.0,69.0,64.0,61.0,59.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
1,The Notorious B.I.G.,13.0,10.0,20.0,4.0,25.0,15.0,8.0,15.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Tupac,20.0,24.0,31.0,41.0,21.0,29.0,25.0,14.0,28.0,...,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Eminem,23.0,39.0,21.0,9.0,13.0,6.0,16.0,26.0,8.0,...,0.0,0.0,5.0,1.0,3.0,5.0,5.0,5.0,5.0,0.0
4,Kendrick Lamar,37.0,14.0,10.0,19.0,10.0,19.0,15.0,6.0,15.0,...,3.0,4.0,0.0,4.0,2.0,0.0,0.0,0.0,0.0,5.0

In [5]:
#df.set_index('Artist Name', inplace=True)
df[['kill']]

     kill
0    14.0
1     0.0
2     6.0
3     4.0
4     4.0
..    ...
121   NaN
122   NaN
123   NaN
124   NaN
125   NaN

[126 rows x 1 columns]

In [6]:
csv = pd.read_csv('/home/lettuce/MyCode/pandasproject/rap_end.csv')
dropper = ['the','you','i','dont','a','know','way','when','to','me','it','my','and','in','up','on','your','of','im','that','with','like','is','we','but','this','all','just','be','got','for','what','do','yeah','no','now','thats','they','never']
csv_drop = csv.drop(dropper, axis=1)
csv_drop.head()

,Artist Name,get,its,nigga,see,cause,if,back,aint,was,...,fame,flock,times,normal,am,wanted,godzilla,breath,lamar,liveget
0,Total,87.0,77.0,72.0,69.0,61.0,61.0,59.0,59.0,58.0,...,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
1,The Notorious B.I.G.,10.0,20.0,28.0,15.0,15.0,17.0,8.0,8.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Tupac,24.0,24.0,18.0,29.0,14.0,15.0,19.0,28.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Eminem,39.0,26.0,0.0,6.0,26.0,14.0,23.0,8.0,15.0,...,5.0,1.0,3.0,5.0,2.0,5.0,5.0,5.0,0.0,0.0
4,Kendrick Lamar,14.0,7.0,26.0,19.0,6.0,15.0,9.0,15.0,17.0,...,0.0,4.0,2.0,0.0,3.0,0.0,0.0,0.0,5.0,5.0

In [99]:
era = [2,2,3,4,2,2,2,2,3,4,4,3,3,3,1,4,2,4,3,4,4,5,3,4,4,2,4,4,4,3,4,4,4,2,4,4,4,3,4,3,4,4,4,4,3,4,2,4,3,4,1,3,2,2,2,1,4,2,2,2,3,2,2,2,5,3,2,4,2,3,4,3,4,1,2,2,3,5,4,4,5,3,2,5,1,3,5,3,2,2,5,5,4,1,1,1,3,3,3,4,4,5,5,5,1,1,1,1,1,5,5,5,5,5,5,5,5,5,5,4,1]
y = 0
era.insert(56,1)

for x in range(1,6):
    print(era.count(x))
    y += era.count(x)
y

15
26
24
36
21

122

In [89]:
era_fix = []

for x in range(0,121):
    if era[x] == 0:
        era_fix.append('0')
    if era[x] == 1:
        era_fix.append('1980s')
    elif era[x] == 2:
        era_fix.append('1990s')
    elif era[x] == 3:
        era_fix.append('2000s')
    elif era[x] == 4:
        era_fix.append('2010s')
    elif era[x] == 5:
        era_fix.append('2020s')
era_fix

['1990s',
 '1990s',
 '2000s',
 '2010s',
 '1990s',
 '1990s',
 '1990s',
 '1990s',
 '2000s',
 '2010s',
 '2010s',
 '2000s',
 '2000s',
 '2000s',
 '1980s',
 '2010s',
 '1990s',
 '2010s',
 '2000s',
 '2010s',
 '2010s',
 '2020s',
 '2000s',
 '2010s',
 '2010s',
 '1990s',
 '2010s',
 '2010s',
 '2010s',
 '2000s',
 '2010s',
 '2010s',
 '2010s',
 '1990s',
 '2010s',
 '2010s',
 '2010s',
 '2000s',
 '2010s',
 '2000s',
 '2010s',
 '2010s',
 '2010s',
 '2010s',
 '2000s',
 '2010s',
 '1990s',
 '2010s',
 '2000s',
 '2010s',
 '1980s',
 '2000s',
 '1990s',
 '1990s',
 '1990s',
 '1980s',
 '1980s',
 '2010s',
 '1990s',
 '1990s',
 '1990s',
 '2000s',
 '1990s',
 '1990s',
 '1990s',
 '2020s',
 '2000s',
 '1990s',
 '2010s',
 '1990s',
 '2000s',
 '2010s',
 '2000s',
 '2010s',
 '1980s',
 '1990s',
 '1990s',
 '2000s',
 '2020s',
 '2010s',
 '2010s',
 '2020s',
 '2000s',
 '1990s',
 '2020s',
 '1980s',
 '2000s',
 '2020s',
 '2000s',
 '1990s',
 '1990s',
 '2020s',
 '2020s',
 '2010s',
 '1980s',
 '1980s',
 '1980s',
 '2000s',
 '2000s',
 '2000s',
 '2010s',
 '2010s',
 '2020s',
 '2020s',
 '2020s',
 '1980s',
 '1980s',
 '1980s',
 '1980s',
 '1980s',
 '2020s',
 '2020s',
 '2020s',
 '2020s',
 '2020s',
 '2020s',
 '2020s',
 '2020s',
 '2020s',
 '2020s',
 '2010s']

In [90]:
rap = pd.read_csv('/home/lettuce/MyCode/pandasproject/rap.csv')
rap['Era'] = era_fix

In [91]:
rap.tail(60)

                   Rap Name      Rap Like    Era
61                Rick Ross  51,444 votes  2000s
62                   Twista  34,152 votes  1990s
63                  Big Pun  28,002 votes  1990s
64                  Raekwon  24,683 votes  1990s
65                    J.I.D  23,725 votes  2020s
66                   Xzibit  44,070 votes  2000s
67                 Scarface  33,305 votes  1990s
68                Lil Dicky   5,383 votes  2010s
69               Will Smith  26,314 votes  1990s
70                  Mos Def  34,456 votes  2000s
71                   Hopsin  27,285 votes  2010s
72                  Big Boi  32,577 votes  2000s
73                   G-Eazy  61,228 votes  2010s
74               Slick Rick  29,938 votes  1980s
75                      GZA  22,168 votes  1990s
76                    Q-Tip  23,304 votes  1990s
77                  Prodigy  35,486 votes  2000s
78              Post Malone  26,074 votes  2020s
79               Young Thug  24,176 votes  2010s
80                       NF  17,992 votes  2010s
81                 Lil Baby  13,537 votes  2020s
82                   T-Pain  15,293 votes  2000s
83                   Coolio  14,119 votes  1990s
84                   Polo G   9,695 votes  2020s
85                   MC Ren   9,646 votes  1980s
86              Lupe Fiasco  17,836 votes  2000s
87                    Quavo   9,582 votes  2020s
88                   Common  17,586 votes  2000s
89                     E-40  31,916 votes  1990s
90                  Fat Joe  19,617 votes  1990s
91              Roddy Ricch  47,404 votes  2020s
92                   DaBaby  20,355 votes  2020s
93                       YG  14,664 votes  2010s
94        Grandmaster Flash   7,459 votes  1980s
95                  KRS-One  10,139 votes  1980s
96           Big Daddy Kane  16,006 votes  1980s
97        Pharrell Williams  15,556 votes  2000s
98                  Juicy J  50,620 votes  2000s
99                   Kurupt  28,500 votes  2000s
100           Vince Staples  16,261 votes  2010s
101             Nicki Minaj  19,098 votes  2010s
102  A Boogie wit da Hoodie  10,280 votes  2020s
103           Playboi Carti   4,784 votes  2020s
104              NLE Choppa   5,818 votes  2020s
105                   N.W.A           NaN  1980s
106            Public Enemy           NaN  1980s
107             Kurtis Blow            ""  1980s
108              De La Soul            ""  1980s
109                 Chuck D            ""  1980s
110                Doja Cat            ""  2020s
111             Jack Harlow            ""  2020s
112               lil nas x            ""  2020s
113                lil Durk            ""  2020s
114               Baby Keem            ""  2020s
115               JPEGMAFIA            ""  2020s
116             Death Grips            ""  2020s
117            BROCKHAMPTON            ""  2020s
118                     JID           NaN  2020s
119            Denzel Curry            ""  2020s
120           Isaiah Rashad            ""  2010s

In [97]:
#remove Rap Like column from df
#rap = rap.drop(['Rap Like'], axis=1)
#rap.head()

#write to csv
rap.to_csv('/home/lettuce/MyCode/pandasproject/rap_hold.csv', index=False)